### ISSUE TITLE
No functionality on Nexus 5

### ISSUE THREAD

**Issue by KevinGimbel** [opoloo/maxdown#41]
When installing Maxdown via Firefox there's no functionality after launching the App from the Homescreen or Menu. It stays blank, doesn't show the "default" Document and I'm unable to add new documents. The same happens when I open the "Web App" - nothing is accessible at the moment.

Android 5.1.1
Firefox 38.0.1

**Comment by MyXoToD** [comment]
There was a problem with the offline appcache when we added the dropbox api. This should be fix by now. For me it's working fine again on desktop and mobile.

**Desktop**
Chromium v43.0.2357.81
Chrome v43.0.2357.130
Firefox v38.0

**Mobile**
Chrome v43.0.2357.93
Firefox v38.0

**Comment by MyXoToD** [comment]
Another important thing: The app makes use of local appcache, so if we push a new version you may delete the offline cache. It sometimes seems to be a problem to refresh the code itself...
